### ISSUE TITLE
.jar files are empty

### ISSUE THREAD

**Issue by arman-ygh** [Cryptolens/cryptolens-java#28]
Hello, 

After downloading and adding the latest .jar file, the classes in .iocryptolens are empty. I tried multiple versions now, but could not succeed. When is the maven release planned?

My errors: 

 Exception in thread "main" java.lang.NoClassDefFoundError: io/cryptolens/models/ActivateModel
	at main.Main.validateKey(Main.java:111)
	at main.Main.initializeConfig(Main.java:97)
	at main.MainMenu.<init>(MainMenu.java:62)
	at main.Main.main(Main.java:75)
Caused by: java.lang.ClassNotFoundException: io.cryptolens.models.ActivateModel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)

**Comment by artemlos** [comment]
Sorry, I forgot to answer the Maven question :)

There is currently no date set when it will be released, but it is being worked on. You can follow the progress in the following issue: https://github.com/Cryptolens/cryptolens-java/issues/20

@ArmanYeghiazaryan
